### ISSUE TITLE
`list` only lists enabled layouts

### ISSUE THREAD

**Issue by TamasBarta** [Lutzifer/keyboardSwitcher#11]
Thank you for this tool! 🙂

I'm trying to use this tool as part of my effort to script my initial macOS setup. I noticed when testing that `keyboardSwitcher list` lists the same as `keyboardSwitcher enabled`, which are configured under System Settings. This is problematic for me, because that's exactly what I want to set up in a scripted way 😅

Do you think this can be achieved with this tool? Also, I believe `keyboardSwitcher list` should work differently, so this is also a bug report.

Env:
OS: macOS 14.4 Sonoma
Mac: MacBook Pro 14, 2021, Apple M1 Pro

**Comment by Lutzifer** [comment]
thanks for the bugreport!

this either has never really worked or (more likely) was changed in one of the more recent macOS updates.

this is fixed in the newly released v2.1.0

**Comment by TamasBarta** [comment]
Amazing! Thanks! I'll check soon.

Edit: I can confirm it works on my computer too. Thanks again.
