### ISSUE TITLE
Unable to switch to Japanese/Hiragana/Kana

### ISSUE THREAD

**Issue by joobei** [Lutzifer/keyboardSwitcher#5]
I am unable to switch to Japanese through keyboardSwitcher (I can through the UI). I can switch to my other two installed languages but not Japanese.

> $ keyboardSwitcher select Kana    
> Failed to set the layout "com.apple.keylayout.KANA".
> Layout "com.apple.keylayout.KANA" known, but could not be set: Please add the layout in System Preferences.app > Keyboard > Input Sources to fix this.

Could this be related to #3 ?

**Comment by Lutzifer** [comment]
I finally released a new version.

When adding Japanese, I can select Katakana using 

`
keyboardSwitcher select Katakana
`

Does this solve your issue?

**Comment by joobei** [comment]
Katakana did not work but Hiragana worked yes. Thank you very much! :)
