### ISSUE TITLE
Switching keyboard sometimes not having any effect

### ISSUE THREAD

**Issue by dvcrn** [Lutzifer/keyboardSwitcher#6]
I am trying to switch between English <> Japanese <> Korean <> Chinese. I have a few hotkeys in keyboard masetro set to execute keyboardSwitcher with the target keyboard. 

The menubar item is usually getting changed just fine, but sometimes the keyboard still types in the previous language until I tab into a different app. For example just now I can switch to Japanese, but when I try to switch to Chinese or Korean, it just writes in English

**Comment by Lutzifer** [comment]
Sorry for the late answer.

If you are already in KeyboardMaestro, you should be able to directly change the layout using KeyboardMaestros System Control -> Set Keyboard Layout Action.

**Comment by dvcrn** [comment]
Hey, the problem is that switching between languages that use different characters isn't working correctly in most cases when directly activating them through system commands. I am currently using a workaround in keyboardmaestro but was hoping you found a way to get by it 

My workaround activates the languages, then switches back and forth once to actually fully active it. If I don't do that, it happens often that the menuicon shows that I am in Japanese/Korean/Chinese but the typing is still in English. 

<img width="670" alt="screen shot 2018-04-06 at 8 57 09" src="https://user-images.githubusercontent.com/688326/38404574-fe82222a-39a5-11e8-9976-0055ea7f1818.png">

**Comment by Lutzifer** [comment]
Can you give me the commands you are using?

**Comment by Lutzifer** [comment]
another alternative for you to try could be https://github.com/utatti/kawa

**Comment by dvcrn** [comment]
Thanks, I am going to give kawa a try. 

This looks like the issue I was talking about: https://github.com/utatti/kawa/issues/11
