### ISSUE TITLE
Provide compiled binaries

### ISSUE THREAD

**Issue by NightMachinery** [Lutzifer/keyboardSwitcher#8]
Building this requires xcode, which takes a lot of space, needs constant updates, and can only be downloaded through Apple's shitty downloaders which don't work on any but the best internet connections.
```
xcodebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by dankuri** [comment]
+1

**Comment by fedor-ivn** [comment]
+1

**Comment by whatwouldmarvindo** [comment]
yes please

**Comment by Lutzifer** [comment]
Resolved via https://github.com/Lutzifer/homebrew-tap/commit/11bb803f1d96bd2908b287356d0fbcefd6c59783
